#!/usr/bin/bash
shopt -s extglob
# export LC_COLLATE=C
: '
======= case syntax ========
case <var> in
"case1")
	//logic
	;;
"case2")
	//logic
	;;
*)
	//logic
esac
======= case syntax ========
'

#read -p "Please Enter Your Name: " name
: ' 
case $name in
"mahmoud")
	echo Hello Manager
	;;
"ahmed")
	echo Hello Supervisor
	;;
*)
	echo UNKNOWN USER
esac

case $name in
m*)
	echo Hello Manager
	;;
a*)
	echo Hello Supervisor
	;;
*)
	echo UNKNOWN USER
esac
?(pattern): match zero or one occurrence 
*(pattern): match zero or more occurrence
+(pattern): match one or more occurrence
@(pattern): match only one occurrence
!(pattern): match anything except this pattern


read -p "Please write any word: " word
case $word in
@([010|012|011])+([a-z]))
	echo small letters
	;;
+([A-Z]" "))
	echo capital letters
	;;
+([A-z]))
	echo mixed letters
	;;	
+([0-9]))
	echo numbers
	;;
*)
	echo UNKNOWN USER
esac

while <condition>
do
	// logic
done

until <condition>
do
	//logic
done

num=0
while [ $num -lt 10 ]
do
	echo $num
	((num++))
done

num=0
until [ $num -gt 10 ]
do
	echo $num
	((num++))
done

while true
do
read -p "Please write any word: " word
case $word in
[Ee][Xx][Ii][Tt])
read -p "Do you want to exit (y/n): " check

if [[ "yes" =~ $check ]]
then
	break
fi
	;;
@([010|012|011])+([a-z]))
	echo small letters
	;;
+([A-Z]" "))
	echo capital letters
	;;
+([A-z]))
	echo mixed letters
	;;	
+([0-9]))
	echo numbers
	;;
*)
	echo UNKNOWN USER
esac
done

for <var> in <list>
do

done



for name in ahmed mahmoud mohamed mina
do
echo $name
done


for files in `ls $1/*`
do
	chmod u-x $files
done

PS3="ENTER YOUR VALUE#? "
select name in mahmoud ahmed mina exit
do
case $name in
"mahmoud")
	echo Hello Manager
	;;
"ahmed")
	echo Hello Supervisor
	;;
"mina")
	echo Hello Supervisor
	;;
"exit")
	break
	;;
*)
	echo UNKNOWN USER
esac
done


Arrays
Function
project


declare -a arr=(1 9 78 55 87) to declare array




declare -a arr=(1 9 78 55 87) 
echo ${arr[@]} # print all elem in array
echo ${arr[0]} # get first elem
echo ${arr[@]: -1} # get last elem in array
echo ${#arr[@]} 


read -p "enter array size: " size
sum=0
for ((i=0;i<$size;i++))
do
	read -p "please enter elem $((i+1)): " arr[$i]
	((sum+=${arr[$i]}))
done
echo ${arr[@]}
echo $sum
((avg=$sum/$size))
echo $avg

for num in $@
do
	echo $num
done


function hello(){
	sum=100000
	echo in hello function
}

hello 
echo $sum

hello(){
	sum=100000
	echo in hello function
}

hello 
echo $sum


hello(){
	sum=10
	return $sum
}

hello 
echo $?
echo $?


hello(){
	sum=10000
	echo $sum
}

result=$(hello)
echo $result
'










